Path=C:/Users/Thamodi Walpola/Desktop/Jasper Reports/PhysicalVerification_Obslete_FIFO_new (1).jrxml
Path_LINUX=/home/niro/jrxmls/oracle/PhysicalVerification_Obslete_FIFO_new.jrxml
Path_Damage=C:/Users/Thamodi Walpola/Desktop/Jasper Reports/PhysicalVerification_Damage_FIFO_new.jrxml
Path_Damage_LINUX=/home/niro/jrxmls/oracle/PhysicalVerification_Damage_FIFO_new.jrxml